[package]
name = "bevy-voxel-game"
version = "0.2.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = [
    "dynamic_linking", 
    "bevy_dev_tools"
] }

bevy-inspector-egui = "0.35"
bevy_rapier3d = { version = "0.32.0", features = ["simd-stable"] }
fastnoise-lite = "1.1.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.dev-optimized]
inherits = "dev"
opt-level = 3

[profile.release]
opt-level = 3
codegen-units = 1